### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by CodesDoWork** [blz-it/blz-it.de#19]
We need a page on which our whole blz-it-team is displayed.

 - [X] Create Page
 - [x] Navigation
 - [x] Translation
 - [x] Proper data format
 - [x] Proper data
 - [ ] Background photo

**Comment by styrix560** [comment]
show
  - picture
  - name
  - last role
    - "and more" if person participated in more than one event

**Comment by styrix560** [comment]
Todo:
 - [ ] Navigation
 - [ ] Translation
 - [ ] Proper data format
 - [ ] Proper data
