### ISSUE TITLE
Localize 404 page

### ISSUE THREAD

**Issue by CodesDoWork** [blz-it/blz-it.de#25]

**Comment by CodesDoWork** [comment]
After some research, I think the only possible solution is to use React for to localize the 404 page...

**Comment by Benjamin-Frost** [comment]
> After some research, I think the only possible solution is to use React for to localize the 404 page...

If it's possible in React then it must be possible in vanilla JavaScript as well :D But React is fine for me

**Comment by CodesDoWork** [comment]
On the branch for this issue, I managed to translate the main element of the page but not Header nor Footer. I don't know how I could do this...
