### ISSUE TITLE
Update website data

### ISSUE THREAD

**Issue by styrix560** [blz-it/blz-it.de#272]
We should update the dates for the upcoming years.
Also we should add Daniel's and Simon's achievements at the WSC 2024.

**Comment by JonasWanke** [comment]
Our next German Championships will be from June 2 to 5, 2025. The AEC 2026 doesn't have an exact date yet (will probably be decided just before the championships)

**Comment by JonasWanke** [comment]
Registration starts on 2024-11-01, online competition is 2024-12-28/2025-02-28

**Comment by styrix560** [comment]
> Registration starts on 2024-11-01, online competition is 2024-12-28/2025-02-28

Is there an end date for the registration?

**Comment by JonasWanke** [comment]
Yes: 2025-02-21
