### ISSUE TITLE
Update registration form

### ISSUE THREAD

**Issue by JonasWanke** [blz-it/blz-it.de#279]
- [x] remove personal street, zip code
- [x] make personal city mandatory
- [x] maybe rename Beruf → Beschäftigung?
- [x] depending on that choice, show the remaining fields:
  - Auszubildende*r: Unternehmen, optional Universität/Hochschule
  - Schüler*in: Schule
  - Student*in: Universität/Hochschule, optional Unternehmen
  - Angestellte*r: Unternehmen
  - each of these only has name and city, not street or zip code

**Comment by JonasWanke** [comment]
The registration form should be reachable at blz-it.de/anmeldung (so that we can use that URL on our flyer) and be prominently featured on our landing page

**Comment by styrix560** [comment]
This will be not as easy as we thought it would be. It is possible, that we will have to rewrite most of the form, because I do not know how many breaking changes react has after we updated of our dependencies.

**Comment by Benjamin-Frost** [comment]
> This will be not as easy as we thought it would be. It is possible, that we will have to rewrite most of the form, because I do not know how many breaking changes react has after we updated of our dependencies. I will focus on the other issues for now.

AFAIK, React didn't have any breaking changes from `v18.0` to `v18.3`. I can give this issue a shot if you want.

**Comment by JonasWanke** [comment]
The API is available at https://registration-api.blz-it.de/
