### ISSUE TITLE
Skill09 Page

### ISSUE THREAD

**Issue by benjamin-frost** [blz-it/blz-it.de#6]
Title: IT Software Solutions for Business

Content:

- Images/Videos
- Current national team
- Previous competitors
- Trainers/Expert

**Comment by CodesDoWork** [comment]
@Benjamin-Frost @JonasWanke Only content is missing here

**Comment by Benjamin-Frost** [comment]
> @Benjamin-Frost @JonasWanke Only content is missing here

Jonas sent me some information, and I will try to set the page up :)
